module.exports = {
  BOOKING_SLOT_MINUTES: 30,
  BOOKING_GRACE_MINUTES: 10,
  SESSION_MIN_BALANCE_BASE_VND: 200000,
  SESSION_SOC_RANDOM_MIN: 30,
  SESSION_SOC_RANDOM_MAX: 70,
  SESSION_IDLE_FEE_INTERVAL_MINUTES: 10,
};
