const BOOKING_STATUS = {
  RESERVED: "RESERVED",
  CHECKED_IN: "CHECKED_IN",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
};
const SESSION_STATUS = {
  PENDING: "PENDING",
  CHARGING: "CHARGING",
  COMPLETED: "COMPLETED",
  STOPPED: "STOPPED",
};
const VEHICLE_PLUG_TYPES = ["CCS2", "CHAdeMO", "AC_Type2", "GB/T", "Other"];
const TARIFF_CONNECTOR_TYPES = ["DC_CCS2", "CHAdeMO"];
const PAYMENT_METHODS = {
  WALLET: "WALLET",
  ONSITE: "ONSITE",
};
const INCIDENT_SEVERITY = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const INCIDENT_STATUS = ["OPEN", "IN_PROGRESS", "RESOLVED"];
module.exports = {
  ROLES: {
    ADMIN: "admin",
    STAFF: "staff",
    DRIVER: "driver",
  },
  STATION_STATUS: ["ONLINE", "OFFLINE", "MAINTENANCE"],
  CONNECTOR_STATUS: ["OFFLINE", "IDLE", "RESERVED", "CHARGING", "FINISHED"],
  TARIFF_MODE: ["energy", "time", "hybrid"],
  BOOKING_STATUS,
  CHARGER_STATUS: ["ONLINE", "OFFLINE", "MAINTENANCE"],
  BOOKING_STATUS_VALUES: Object.values(BOOKING_STATUS),
  SESSION_STATUS,
  SESSION_STATUS_VALUES: Object.values(SESSION_STATUS),
  VEHICLE_PLUG_TYPES,
  TARIFF_CONNECTOR_TYPES,
  PAYMENT_METHODS,
  INCIDENT_SEVERITY,
  INCIDENT_STATUS,
};
